### ISSUE TITLE
Love this user interface - can it be modified to work for local playback?

### ISSUE THREAD

**Issue by ghost** [NicolasHaeffner/plugin.audio.connectcontrol#1]
I love the look and feel of this spotify player. This looks awesome!

I've been searching for a Kodi 17 skin that uses a similar layout for the locally playing music on the device. This is because I'm using a pi for my car stereo. So far I can't find anything with big album art pictures or easy to hit play / pause buttons.

Any chance you could help me modify the skin so that the info and buttons are for the local music on the device?

**Comment by NicolasHaeffner** [comment]
So I have been abandoning this project for quite some time, sorry for that. 
I guess it is possible to change it for local playback but it is not at all something i am keen on figuring out because I really don't need it. 
But if you want to do it yourself or you find someone who does it I am happy to help.
